USE [HYT]

GO

SET ANSI_PADDING ON


GO
-- Index Phần của Huy

CREATE NONCLUSTERED INDEX [LSN_MASP_Index] ON [dbo].[LICHSUNHAP]
(
	[MASP] ASC
)
GO
CREATE NONCLUSTERED INDEX [LSN_NGAYNHAP_Index] ON [dbo].[LICHSUNHAP]
(
	[NGAYNHAP] ASC
)
GO
CREATE NONCLUSTERED INDEX [LSX_NGAYLAP_Index] ON [dbo].[DONHANG]
(
	[NGAYLAP] ASC
)
GO
CREATE NONCLUSTERED INDEX [QL_TIMSP_THEOTEN_Index] ON [dbo].[SANPHAM]
(
	[TENSP] ASC
)
GO

-- Index Phần của Đức
CREATE NONCLUSTERED INDEX [TimKiemSP_index] ON [dbo].[SANPHAM]
(
	[THANHPHANCHINH] ASC
)
GO

CREATE NONCLUSTERED INDEX [TenDangNhap_index] ON [dbo].[TAIKHOAN]
(
	[TENDN] ASC
)
GO
---INDEX CỦA BÌNH MINH ĐẸP TRAI NHẤT NHÓM
CREATE NONCLUSTERED INDEX [DH_NGAYNHAP_index] ON [dbo].[DONHANG]
(
	[NGAYLAP] ASC
)